#!/bin/bash

docker build \
    --build-arg VCS_REF=$SOURCE_COMMIT \
    --build-arg BUILD_DATE=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) \
    --build-arg TRANSMISSION_VERSION=$(docker run --rm -i alpine:latest sh -c 'apk update -q && apk search -x transmission-daemon' | awk -F[-] '{print $3}') \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
