#!/bin/bash

VERSION=$(docker inspect --format '{{ index .Config.Labels "org.label-schema.version"}}' $IMAGE_NAME)
MAJOR_VERSION=${VERSION%.*}

docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$VERSION

docker tag $IMAGE_NAME $DOCKER_REPO:$MAJOR_VERSION
docker push $DOCKER_REPO:$MAJOR_VERSION
