name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Nightly to capture latest base image and transmission version
  schedule:
    - cron:  '* 21 * * *'

  # Run tests for any PRs.
  pull_request:

  # Allow to trigger manually from github ui
  workflow_dispatch:

jobs:
  dockerhub-registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Transmission version
        id: version
        run: |
          TRANSMISSION_VERSION=$(docker run --rm -i registry.access.redhat.com/ubi9-minimal sh -c 'rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && microdnf repoquery transmission-daemon' | tail -n 1 | awk -F[-] '{print $3}')
          TRANSMISSION_MAJOR_VERSION=${TRANSMISSION_VERSION%.*}

          echo "full=$TRANSMISSION_VERSION" >> $GITHUB_OUTPUT
          echo "major=$TRANSMISSION_MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            tingvarsson/transmission
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=${{ steps.version.outputs.full }}
            type=raw,value=${{ steps.version.outputs.major }}
            type=sha,format=long,prefix=
          labels: |
            org.opencontainers.image.version=${{ steps.version.outputs.full }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
